### ISSUE TITLE
Specifying the number of MC samples

### ISSUE THREAD

**Issue by mortonjt** [jsilve24/fido#10]
Right now, pibble will return 2000 monte carlo samples from the posterior distribution.

Is it possible to specify an arbitrary number of samples to draw from the posterior distribution?

**Comment by jsilve24** [comment]
sorry for delay. 

All of the fitting functions accept an n_samples integer argument. 

Justin

**Comment by mortonjt** [comment]
Ahhh, I see it : https://jsilve24.github.io/fido/reference/optimPibbleCollapsed.html
Thanks!
