### ISSUE TITLE
coef.pibblefit not exported from namespace

### ISSUE THREAD

**Issue by jsilve24** [jsilve24/fido#12]
Someone emailed me this bug report:

We have some troubles with the function "coef" (Error: Error in UseMethod("coef") :  no applicable method for 'coef' applied to an object of class "pibblefit" ). 

The code used is the following: 

 sim <- pibble_sim(D=10, N=100, Q=3)
 fit <- pibble(Y=sim$Y, X=sim$X)
 coef(fit)

temporary workaround is to call fido:::coef.pibblefit(fit)

**Comment by michellepistner** [comment]
Error should be fixed in the most recent commit.
